#!/bin/sh
DIR=$1

sed -f $DIR/subst Robot.java > $DIR/Robot.java || exit 1
sed -f $DIR/subst Main.java > $DIR/Main.java || exit 1
cd $DIR || exit 1
cp program Fourmi.java || exit 1
javac Main.java || exit 1
exec java Main
