#!/bin/sh

mod_info()
{
    need_command gplc
}

mod_prep()
{
    fetch_t robot.pl
    spawn program.pl
}

mod_run()
{
    gplc --no-top-level robot.pl program.pl -o program 1>&2 || error
    exec ./program
}
