#!/bin/sh
MOD_LIB=$1

mod_api()
{
    echo api: $1
}

need_command()
{
    which $1 > /dev/null 2> /dev/null || exit 1
}

error()
{
    exit 1
}

fetch()
{
    cp $MOD_LIB/$1 > $1 || error
}

fetch_t()
{
    sed -f subst $MOD_LIB/$1 > $1 || error
}

spawn()
{
    [ "$1" != "program" ] && mv program $1 || error
}

laby_name()
{
    $(echo 'laby_name_'$1 | sed -f subst)
}

. $MOD_LIB/defs

case $2 in
  info) mod_info;;
  prep) mod_prep;;
  run) mod_run;;
  *) exit 2;;
esac
