#!/bin/sh

mod_info()
{
    need_command gcc
}

mod_prep()
{
    fetch_t robot.c
    fetch_t robot.h
    spawn program.c
}

mod_run()
{
    gcc -Wall robot.c program.c -o program || error
    exec ./program
}
